// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"login-api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/login/index",
				Handler: IndexHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/auth",
				Handler: AuthHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/verify-code",
				Handler: VerifyCodeHandler(serverCtx),
			},
		},
	)
}
