// Code generated by goctl. DO NOT EDIT!
// Source: login.proto

package server

import (
	"context"

	"login-rpc/internal/logic"
	"login-rpc/internal/svc"
	"login-rpc/proto"
)

type LoginServer struct {
	svcCtx *svc.ServiceContext
}

func NewLoginServer(svcCtx *svc.ServiceContext) *LoginServer {
	return &LoginServer{
		svcCtx: svcCtx,
	}
}

func (s *LoginServer) Submit(ctx context.Context, in *proto.Request) (*proto.Response, error) {
	l := logic.NewSubmitLogic(ctx, s.svcCtx)
	return l.Submit(in)
}
