// Code generated by goctl. DO NOT EDIT!
// Source: login.proto

//go:generate mockgen -destination ./login_mock.go -package login -source $GOFILE

package login

import (
	"context"

	"login-rpc/proto"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	Request   = proto.Request
	Response  = proto.Response
	UserToken = proto.UserToken

	Login interface {
		Submit(ctx context.Context, in *Request) (*Response, error)
	}

	defaultLogin struct {
		cli zrpc.Client
	}
)

func NewLogin(cli zrpc.Client) Login {
	return &defaultLogin{
		cli: cli,
	}
}

func (m *defaultLogin) Submit(ctx context.Context, in *Request) (*Response, error) {
	client := proto.NewLoginClient(m.cli.Conn())
	return client.Submit(ctx, in)
}
