// Code generated by goctl. DO NOT EDIT.
package types

type HttpResponse struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type IndexResp struct {
	HttpResponse
}

type AuthReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AuthResp struct {
	Ticket    string `json:"ticket"`
	ExpiresIn int32  `json:"expires_in"`
}

type VerifyCodeResp struct {
	Data string `json:"data"`
}
